apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: docs
  annotations:
    github.com/project-slug: csquire/docs
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: unknown
  owner: infrastructure
